config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'} 
  devise_for :admins, skip: [:registrations] , controllers: {sessions: 'admins/sessions'} 

  namespace :admin do
    root to: "home#index"
    resources :admins
    resources :users, only: [:index]
    resources :posts, only: [:index, :show]
  end
  root to: "user/timeline#index"
  namespace :user do 
    get 'profile', to: "profile#show"
    get 'potential_to_follow', to: "profile#potential_to_follow"
    get 'following', to: "profile#following"
    get 'followers', to: "profile#followers"
    resources :users, only: [:show]
    resources :posts, only: [:create, :destroy] do 
      member do 
        post :like_toggle
      end
    end

    post 'follow/:id', to: "subscriptions#follow", as: :follow
    post 'unfollow/:id', to: "subscriptions#unfollow", as: :unfollow
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord 
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :body, presence: true

  def liked_by_user?(user) 
    likes.where(user: user).present? 
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord 
  belongs_to :followed, class_name: "User"
  belongs_to :followed_by, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, :name, :avatar, presence: true
  
  has_one_attached :avatar
  has_many :posts
  has_many :likes
    
  has_many :followers_subscriptions, foreign_key: :followed_id, class_name: "Subscription"
  has_many :followers, through: :followers_subscriptions, source: :followed_by

  has_many :following_subscriptions, foreign_key: :followed_by_id, class_name: "Subscription"
  has_many :following, through: :following_subscriptions, source: :followed

  scope :potential_to_follow, -> (user) { where.not(id: user.following.pluck(:id)).where.not(id: user.id) }
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < AdminController
  before_action :set_admin, only: [:edit, :show, :update, :destroy]
  def index 
    @admins = Admin.order(id: :desc)
  end

  def new 
    @admin = Admin.new
  end

  def create 
    @admin = Admin.new(admin_params)
    if @admin.save 
      redirect_to admin_admins_path, notice: 'Admin criado com sucesso!'
    else
      render :new
    end
  end

  def edit 
    
  end

  def update 
    params = admin_params.to_h
    params = params.except!(:password, :password_confirmation) if params[:password].blank?

    if @admin.update(params) 
      redirect_to admin_admins_path, notice: 'Admin editado com sucesso!'
    else
      render :edit
    end
  end

  def destroy 
    @admin.destroy
    redirect_to admin_admins_path, notice: 'Admin excluido com sucesso!'
  end
  private 

  def admin_params 
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end

  def set_admin 
    @admin = Admin.find(params[:id])
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index 
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  
  def index 
    @posts = Post.order(id: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  
  def index 
    @users = User.order(id: :desc)
  end

  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController 
  before_action :authenticate_admin
  
  def authenticate_admin 
    redirect_to new_admin_session_path unless current_admin?
  end

  def current_admin? 
    if current_admin.present?
      true
    else
      false
    end
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(admin) 
    new_admin_session_path    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController
  skip_before_action :verify_authenticity_token, only: [:like_toggle]

  def create
    p_params = post_params.merge(user: current_user)
    @posts = Post.new(p_params)
    if @posts.save 
      redirect_to user_profile_path
    else
      render "user/profile/show"
    end
  end

  def destroy
    posts = current_user.posts.find(params[:id])
    posts.destroy
    redirect_to user_profile_path
  end

  def like_toggle
    post = Post.find(params[:id])
    like = Like.find_by(user: current_user, post: post)
    if like.present?
      like.destroy
      respond_to do |format|
        format.json { render json: {liked: false, likesCount: post.likes.count} }
      end
    else
      Like.create(user: current_user, post: post)
      respond_to do |format|
        format.json { render json: {liked: true, likesCount: post.likes.count} }
      end
    end
  end
  private 
  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController
  def show
    @post = Post.new
  end

  def potential_to_follow
    @potential_to_follow = User.potential_to_follow(current_user)
  end

  def following 
    @following = current_user.following
  end

  def followers 
    @followers = current_user.followers
  end
end

app/controllers/user/subscriptions_controller.rb
class User::SubscriptionsController < UserController
  def follow 
    user_to_follow = User.find_by_id(params[:id])
    Subscription.create(followed_by: current_user, followed: user_to_follow)

    redirect_to user_potential_to_follow_path
  end

  def unfollow 
    user = User.find_by_id(params[:id])
    subscription = Subscription.find_by(followed_by: current_user, followed: user)
    subscription.destroy
    redirect_to user_following_path
  end
end

app/controllers/user/timeline_controller.rb
class User::TimelineController < UserController
  def index 
    @posts = Post.where(user_id: current_user.following.pluck(:id)).order(created_at: :desc)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < UserController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController 
  before_action :authenticate_user
  
  def authenticate_user 
    redirect_to new_user_session_path unless current_user 
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/_form.html.erb
<div class="card" style="background-color:#f6f6f6;">
  <div class="card-body">
      <%= form_with model: [:admin, admin], local: true do |form| %>
      <%= render "layouts/form_errors", record: admin %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-row">
        <div class="col-6">
          <div class="form-group">
            <%= form.label :password %>
            <%= form.password_field :password, class: 'form-control' %>
          </div>
        </div>
        <div class="col-6">
          <div class="form-group">
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
      </div>
      
        <%= form.submit "Enviar", class: 'btn btn-primary' %>
        <%= link_to 'Voltar', admin_admins_path, class:'btn btn-danger'%>
      
        
    <% end %>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<h3>Editar Administrador</h3>

<%= render "form", admin: @admin %>

app/views/admin/admins/index.html.erb
<%= link_to 'Novo Administrador', new_admin_admin_path, class: 'btn btn-primary mb-4' %>
<h4>Admins</h4><br>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Criado em</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
    <tr>
      <th scope="row"><%= admin.id %></th>
      <td><%= admin.name %></td>
      <td><%= admin.email %></td>
      <td><%= admin.created_at %></td>
      <td><%= link_to "Editar", edit_admin_admin_path(admin), class: 'btn btn-warning btn-sm' %></td>
      <td><%= link_to "Excluir", admin_admin_path(admin),method: :delete, data: {confirm: "Você tem certeza?"},class: 'btn btn-danger btn-sm' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/admins/new.html.erb
<h3>Novo Administrador</h3>

<%= render "form", admin: @admin %>

app/views/layouts/_form_errors.html.erb
<% if record && record.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= t('.error_on_save') %></h4>
    <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<% content_for :content do %>
  <%= render "layouts/admin/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(admin_root_path)? "active" : "" %>">
        <%= link_to("Home", admin_root_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_admins_path)? "active" : "" %>">
        <%= link_to("Administradores", admin_admins_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_users_path)? "active" : "" %>">
        <%= link_to("Usuários", admin_users_path, class: "nav-link") %>
      </li>
      <li class="nav-item <%= current_page?(admin_posts_path)? "active" : "" %>">
      <%= link_to("Posts", admin_posts_path, class: "nav-link") %>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_admin.email %> </div>
        </li>
        <li class="nav-item">
          <%= link_to "Sair", destroy_admin_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialNetworking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= content_for?(:content)? yield(:content) : yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/user.html.erb
<% content_for :content do %>
  <%= render "layouts/user/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>
<%= render template: "layouts/application" %>