config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'} 
  devise_for :admins, skip: [:registrations] , controllers: {sessions: 'admins/sessions'} 

  namespace :admin do
    root to: "home#index"
    resources :admins
    resources :users, only: [:index]
    resources :posts, only: [:index, :show]
  end
  root to: "user/timeline#index"
  namespace :user do 
    get 'profile', to: "profile#show"
    get 'potential_to_follow', to: "profile#potential_to_follow"
    get 'following', to: "profile#following"
    get 'followers', to: "profile#followers"
    resources :users, only: [:show]
    resources :posts, only: [:create, :destroy] do 
      member do 
        post :like_toggle
      end
    end

    post 'follow/:id', to: "subscriptions#follow", as: :follow
    post 'unfollow/:id', to: "subscriptions#unfollow", as: :unfollow
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord 
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :body, presence: true

  def liked_by_user?(user) 
    likes.where(user: user).present? 
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord 
  belongs_to :followed, class_name: "User"
  belongs_to :followed_by, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, :name, :avatar, presence: true
  
  has_one_attached :avatar
  has_many :posts
  has_many :likes
    
  has_many :followers_subscriptions, foreign_key: :followed_id, class_name: "Subscription"
  has_many :followers, through: :followers_subscriptions, source: :followed_by

  has_many :following_subscriptions, foreign_key: :followed_by_id, class_name: "Subscription"
  has_many :following, through: :following_subscriptions, source: :followed

  scope :potential_to_follow, -> (user) { where.not(id: user.following.pluck(:id)).where.not(id: user.id) }
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < AdminController
  before_action :set_admin, only: [:edit, :show, :update, :destroy]
  def index 
    @admins = Admin.order(id: :desc)
  end

  def new 
    @admin = Admin.new
  end

  def create 
    @admin = Admin.new(admin_params)
    if @admin.save 
      redirect_to admin_admins_path, notice: 'Admin criado com sucesso!'
    else
      render :new
    end
  end

  def edit 
    
  end

  def update 
    params = admin_params.to_h
    params = params.except!(:password, :password_confirmation) if params[:password].blank?

    if @admin.update(params) 
      redirect_to admin_admins_path, notice: 'Admin editado com sucesso!'
    else
      render :edit
    end
  end

  def destroy 
    @admin.destroy
    redirect_to admin_admins_path, notice: 'Admin excluido com sucesso!'
  end
  private 

  def admin_params 
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end

  def set_admin 
    @admin = Admin.find(params[:id])
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index 
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  
  def index 
    @posts = Post.order(id: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  
  def index 
    @users = User.order(id: :desc)
  end

  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController 
  before_action :authenticate_admin
  
  def authenticate_admin 
    redirect_to new_admin_session_path unless current_admin?
  end

  def current_admin? 
    if current_admin.present?
      true
    else
      false
    end
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(admin) 
    new_admin_session_path    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/posts_controller.rb
class User::PostsController < UserController
  skip_before_action :verify_authenticity_token, only: [:like_toggle]

  def create
    p_params = post_params.merge(user: current_user)
    @posts = Post.new(p_params)
    if @posts.save 
      redirect_to user_profile_path
    else
      render "user/profile/show"
    end
  end

  def destroy
    posts = current_user.posts.find(params[:id])
    posts.destroy
    redirect_to user_profile_path
  end

  def like_toggle
    post = Post.find(params[:id])
    like = Like.find_by(user: current_user, post: post)
    if like.present?
      like.destroy
      respond_to do |format|
        format.json { render json: {liked: false, likesCount: post.likes.count} }
      end
    else
      Like.create(user: current_user, post: post)
      respond_to do |format|
        format.json { render json: {liked: true, likesCount: post.likes.count} }
      end
    end
  end
  private 
  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < UserController
  def show
    @post = Post.new
  end

  def potential_to_follow
    @potential_to_follow = User.potential_to_follow(current_user)
  end

  def following 
    @following = current_user.following
  end

  def followers 
    @followers = current_user.followers
  end
end

app/controllers/user/subscriptions_controller.rb
class User::SubscriptionsController < UserController
  def follow 
    user_to_follow = User.find_by_id(params[:id])
    Subscription.create(followed_by: current_user, followed: user_to_follow)

    redirect_to user_potential_to_follow_path
  end

  def unfollow 
    user = User.find_by_id(params[:id])
    subscription = Subscription.find_by(followed_by: current_user, followed: user)
    subscription.destroy
    redirect_to user_following_path
  end
end

app/controllers/user/timeline_controller.rb
class User::TimelineController < UserController
  def index 
    @posts = Post.where(user_id: current_user.following.pluck(:id)).order(created_at: :desc)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < UserController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController 
  before_action :authenticate_user
  
  def authenticate_user 
    redirect_to new_user_session_path unless current_user 
  end

  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :configure_sign_up_params

  protected 
  
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :name, :avatar])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home/index.html.erb
<h1>Nhein</h1>

app/views/admin/users/index.html.erb
<h4>Usuários</h4><br>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Telefones</th>
      <th scope="col">Seguidores</th>
      <th scope="col">Seguindo</th>
      <th scope="col">Criado em</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.phone %></td>
      <td><%= user.followers.count %></td>
      <td><%= user.following.count %></td>
      <td><%= user.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
      
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/user/_header.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark" style="background-color:#000080!important;">
  <div class="container" >
    <%= image_tag("logo.png", alt: "logo", class: 'navbar-brand', style: "height:40px;")%>
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(root_path)? "active" : "" %>">
        <a class="nav-link" href=<%= root_path %> >Timeline</a>
      </li>
      <li class="nav-item <%= current_page?(user_followers_path)? "active" : "" %>">
        <a class="nav-link" href=<%= user_followers_path %>>Followers</a>
      </li>
      <li class="nav-item <%= current_page?(user_following_path)? "active" : "" %>">
        <a class="nav-link" href=<%= user_following_path %>>Following</a>
      </li>
      <li class="nav-item" <%= current_page?(user_potential_to_follow_path)? "active" : "" %>">
        <a class="nav-link" href=<%= user_potential_to_follow_path %> >Quem eu posso seguir</a>
      </li>
      <li class="nav-item <%= current_page?(user_profile_path)? "active" : "" %>">
        <a class="nav-link" href=<%= user_profile_path %> >Meu Perfil</a>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_user.email %></div>
        </li>
        <li class="nav-item">
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/user/_post_card.html.erb
    <div class="card text-white bg-dark mb-3 mt-3">
      <div class="card-header">
      <%= image_tag(post.user.avatar, class: "ui-w-100-forced rounded-circle mr-3", style: "width: 30px; height: 30px") %>
      <%= link_to post.user.name, post.user == current_user ? user_profile_path : user_user_path(post.user) %>
        <% if (current_user==post.user) %>
          <%= link_to user_post_path(post), method: :delete, class: "close text-white" do %>
          <span aria-hidden="true">&times;</span>
          <% end %>
        <% end %>
      
      </div>
      <div class="card-body">
        <small class="text-muted"><%= post.created_at.strftime('%d/%m/%Y %H:%M:%S') %></small>
        <p class="card-text"><%= post.body %> </p>
        <%= link_to nil, {class: "like_toggle", id: post.id, remote: true} do %>
          <i style="font-size:18px;color: <%= post.liked_by_user?(current_user) ? "#80c0ff" : "#ffffff" %> " class="fa fa-thumbs-up"></i>
        <% end %>
          <span class="ml-2"><%= post.likes.count %></span>
      </div>
    </div>

app/views/user/_user_card_header.html.erb
<h5 class="card-header">
  <%= image_tag(user.avatar, class: "ui-w-100-forced rounded-circle mr-3", style: "width: 90px; height: 90px") %>
  <%= link_to user.name, user == current_user ? user_profile_path : user_user_path(user) %>
  <br>
  <span style="font-size:14px;">Seguidores:</span> <span style="font-size:16px;" class="badge badge-info mr-3"><%= user.followers.count %></span>
  <span style="font-size:14px;">Seguindo:</span> <span style="font-size:16px;" class="badge badge-info"><%= user.following.count %></span>
  
</h5>

app/views/user/profile/followers.html.erb
<div class="row">
  <% @followers.each do |user| %>
    <div class="col-lg-4">
      <div class="card">
        <%= render("user_card_header", user: user) %>
        <div class="card-body">
          Email:<p class="card-text text-muted"><%= user.email %></p>
          Telefone:<p class="card-text text-muted"><%= user.phone %></p></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/profile/following.html.erb
<div class="row">
  <% @following.each do |user| %>
    <div class="col-lg-4">
      <div class="card">
        <%= render("user_card_header", user: user) %>
        <div class="card-body">
          Email:<p class="card-text text-muted"><%= user.email %></p>
          Telefone:<p class="card-text text-muted"><%= user.phone %></p></p>
          <%= link_to "Deixar de seguir", user_unfollow_path(user), method: :post, class: "btn btn-secondary" %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/profile/potential_to_follow.html.erb
<div class="row">
  <% @potential_to_follow.each do |user| %>
    <div class="col-lg-4">
      <div class="card">
        <%= render("user_card_header", user: user) %>
        <div class="card-body">
          Email:<p class="card-text text-muted"><%= user.email %></p>
          Telefone:<p class="card-text text-muted"><%= user.phone %></p></p>
          <%= link_to "Seguir", user_follow_path(user), method: :post, class: "btn btn-success" %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/profile/show.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <%= render "user_card_header", user: current_user %>
      <div class="card-body">
        Email:<p class="card-text text-muted"><%= current_user.email %></p>
        Telefone:<p class="card-text text-muted"><%= current_user.phone %></p></p>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <%= form_with(model: [:user, @post], local: true) do |f| %>
          <%= render("layouts/form_errors", record: @post) %>
          <div class="form-group">
            <label for="exampleInputEmail1">Texto</label>
            <%= f.text_area :body, rows: 5, class: "form-control", placeholder: "Digite seu texto..." %>
          </div>
            <button type="submit" class="btn btn-primary">Postar</button>
        <% end %>
      </div>
    </div>

    <% current_user.posts.order('created_at desc').each do |post| %>
      <%= render "user/post_card", post: post %>
      
    <% end %>
  </div>
</div>

app/views/user/timeline/index.html.erb
<div class="row">
  <div class="offset-2 col-lg-8">
    <% @posts.each do |post| %>
    <%= render "user/post_card", post: post %>
    <% end %>
  </div>
</div>

app/views/user/users/show.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <%= render "user_card_header", user: @user %>
      <div class="card-body">
        Email:<p class="card-text text-muted"><%= @user.email %></p>
        Telefone:<p class="card-text text-muted"><%= @user.phone %></p></p>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <% @user.posts.order('created_at desc').each do |post| %>
    <%= render "user/post_card", post: post %>
  <% end %>
  </div>
</div>